### ISSUE TITLE
feat: Add i18n utils

### ISSUE THREAD

**Issue by IniZio** [IniZio/usthing-ui#13]
https://github.com/lingui/js-lingui

**Comment by IniZio** [comment]
Or maybe https://github.com/i18next/react-i18next is an even better choice?

**Comment by tricoder42** [comment]
Ah, I see!

Yeah, I'm not planning to add hooks to LinguiJS because I want to move away from React.Context completely in v3. There's still an open [discussion](https://github.com/lingui/js-lingui/issues/390), but most probably there's gonna be just one very simple hook, which will trigger re-render when locale changes.

Anyway, I'm still working on v3, so go with anything you like :)

Cheers 👋

**Comment by IniZio** [comment]
@tricoder42 Many thanks for you support on the issue, still going with i8next for the hooks but your library is really amazing also :blush:
